name: deploy-to-pi

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      CONTAINER_NAME: 7dayspoll
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Stop existing container
        run: |
          docker stop "$CONTAINER_NAME" || true
          docker rm "$CONTAINER_NAME" || true

      - name: Build
        run: |
          docker image prune -f
          docker build -t "$CONTAINER_NAME" .

      - name: Run Discord Bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          docker run -d \
            --name "$CONTAINER_NAME" \
            --restart unless-stopped \
            -e DISCORD_BOT_TOKEN="${DISCORD_BOT_TOKEN}" \
            "$CONTAINER_NAME"
